apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-pv
spec:
  capacity:
    storage: 100Gi # Set the storage
  accessModes:
    - ReadWriteMany # Concurrent access from multiples pods
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/k8s-shared
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s_master_dev
                - k8s_worker01_dev
                - k8s_worker02_dev # Nodess Names

